<a href="https://colab.research.google.com/github/19PA1A0286/AI-Lab/blob/master/experiments_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1)Experiment 1:Numpy**

## **i)Different ways to create a numpy arrays**

**a)create a numpy array using List**

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


**b)Create a numpy array using arange function**


In [2]:
a=np.array([[1,2,3],[98,99,100]])
print(a)

[[  1   2   3]
 [ 98  99 100]]


# **ii)Add,remove,modify array elements**


**a)Create a numpy array using add function.**

In [4]:
f=np.array([4,8,9])
q=np.append(f,[6,5,8])
print(q)

[4 8 9 6 5 8]


**b)Create a numpy array using remove function**

In [ ]:
c=np.delete(f,2)
print(c)


[4 8]


## iii)Artithmetic operations on NumPy array.

In [6]:
import numpy as np
a=([1,2,3])
b=([4,5,6])
num_sum = np.add(a,b)
num_diff = np.subtract(a,b)
num_quo = np.divide(a,b)
num_mod = np.mod(a,b)
num_pow = np.power(a,b)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]


# **iv)slicling and iterating of numpy arrays**

**a)Create a numpy array using Slicing function.**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


**b)Create a numpy array using iterating function.**

In [ ]:
for x in arr:
  print(x)

1
2
3
4
5
6
7


# **v)Matrix opertions on numpy arrays**

In [ ]:
import numpy as np
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
